/**
 * YouTube Login Service — capture authentic Google cookies for yt-dlp
 *
 * Why this exists:
 *   `--cookies-from-browser chrome` is unreliable: file locks while Chrome
 *   is open, missing profiles, DPAPI decrypt failures, Chrome cookies
 *   cleared by the user. YouTube responds with "Sign in to confirm you're
 *   not a bot" on any anonymous-ish request, which we can NOT bypass with
 *   yt-dlp client tricks alone.
 *
 * Strategy:
 *   1. Maintain a dedicated Chromium profile dir (separate from FB profiles)
 *   2. User clicks "Login YouTube" → we spawn that Chrome with the profile
 *      and navigate to accounts.google.com
 *   3. User logs in manually (same UI as a normal browser)
 *   4. We poll cookies until SAPISID is present → user is authenticated
 *   5. Export every google.com + youtube.com cookie to a Netscape-format
 *      cookies.txt file that yt-dlp can read via --cookies <path>
 *   6. ChannelWatcher reads `youtube_cookies_path` from the settings table
 *      on boot and uses --cookies for every yt-dlp invocation
 *
 * Cookies persist across logins as long as the user doesn't click "Logout"
 * in the Settings UI; the profile dir survives app restarts.
 */

const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');
const puppeteer = require('puppeteer-extra');
const StealthPlugin = require('puppeteer-extra-plugin-stealth');

puppeteer.use(StealthPlugin());

// Google account auth cookies — set on .google.com after the user finishes
// the Google login form. Necessary but NOT sufficient: yt-dlp also needs the
// YouTube session cookie on .youtube.com (LOGIN_INFO), which is only created
// AFTER the user lands on a youtube.com page in the post-login redirect.
const GOOGLE_AUTH_COOKIES = ['SAPISID', '__Secure-1PAPISID', '__Secure-3PAPISID'];
const YOUTUBE_SESSION_COOKIE = 'LOGIN_INFO';

// Find Chrome binary (mirrors poster.js findChromeExecutable but standalone)
function findChrome() {
    if (process.env.KINTENSHAUTO_CHROME && fs.existsSync(process.env.KINTENSHAUTO_CHROME)) {
        return process.env.KINTENSHAUTO_CHROME;
    }
    const candidates = [
        'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
        'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        path.join(process.env.LOCALAPPDATA || '', 'Google\\Chrome\\Application\\chrome.exe'),
        'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
    ];
    for (const c of candidates) if (c && fs.existsSync(c)) return c;
    return null;
}

function pickPort() {
    return 30000 + Math.floor(Math.random() * 20000);
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function waitForDebugPort(port, timeoutMs = 15000) {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
        try {
            const res = await fetch(`http://127.0.0.1:${port}/json/version`);
            if (res.ok) {
                const j = await res.json();
                if (j.webSocketDebuggerUrl) return j.webSocketDebuggerUrl;
            }
        } catch { /* keep polling */ }
        await sleep(150);
    }
    throw new Error(`Chrome debug port ${port} did not respond within ${timeoutMs}ms`);
}

// Netscape cookies.txt format:
//   domain<TAB>include_subdomains<TAB>path<TAB>secure<TAB>expiry<TAB>name<TAB>value
function cookiesToNetscape(cookies) {
    const lines = [
        '# Netscape HTTP Cookie File',
        '# Generated by KINTENSHAUTO — do not edit manually',
        ''
    ];
    for (const c of cookies) {
        // Normalize domain: must start with "." for include_subdomains=TRUE
        let domain = c.domain || '';
        const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        if (!domain.startsWith('.') && !domain.startsWith('http')) {
            // Plain "youtube.com" → "youtube.com" with FALSE flag
        }
        const cookiePath = c.path || '/';
        const secure = c.secure ? 'TRUE' : 'FALSE';
        // Session cookies (expires=-1 / null) → set to far-future expiry for yt-dlp
        const expiry = (c.expires && c.expires > 0)
            ? Math.floor(c.expires)
            : Math.floor(Date.now() / 1000) + 3600 * 24 * 365; // 1 year
        const name = c.name || '';
        const value = c.value != null ? String(c.value) : '';
        // Skip cookies with tab/newline in value (Netscape format is tab-separated)
        if (/[\t\n\r]/.test(value) || /[\t\n\r]/.test(name)) continue;
        lines.push([domain, includeSub, cookiePath, secure, expiry, name, value].join('\t'));
    }
    return lines.join('\n') + '\n';
}

/**
 * YouTubeLoginService — manages the dedicated YT profile + cookies file lifecycle.
 *
 * Constructor opts:
 *   - userDataRoot: base directory under which we create youtube-profile/
 *   - cookiesPath:  where to write cookies.txt (passed to yt-dlp later)
 *   - db:           settings table reader/writer for persistence
 */
class YouTubeLoginService {
    constructor({ userDataRoot, cookiesPath, db }) {
        this.profileDir = path.join(userDataRoot, 'youtube-profile');
        this.cookiesPath = cookiesPath;
        this.db = db;
        this._activeProc = null;
        this._activeBrowser = null;
        if (!fs.existsSync(this.profileDir)) {
            fs.mkdirSync(this.profileDir, { recursive: true });
        }
    }

    // Did the user complete a previous login?
    getStatus() {
        const exists = fs.existsSync(this.cookiesPath);
        if (!exists) return { logged_in: false };
        let mtimeMs = null;
        try { mtimeMs = fs.statSync(this.cookiesPath).mtimeMs; } catch {}
        return {
            logged_in: true,
            last_login_at: mtimeMs ? new Date(mtimeMs).toISOString() : null,
            cookies_path: this.cookiesPath
        };
    }

    // Spawn the YouTube login Chrome window. Returns once the user has
    // logged in AND we've successfully written cookies.txt. Times out
    // after `timeoutMs` if the user never finishes (default 10 min).
    async login({ timeoutMs = 10 * 60_000, onLog = () => {} } = {}) {
        if (this._activeBrowser) {
            throw new Error('Login window already open — close it first');
        }
        const chromePath = findChrome();
        if (!chromePath) {
            throw new Error('ไม่เจอ Chrome ในเครื่อง — กรุณาติดตั้ง Google Chrome ก่อน');
        }

        // Clean stale singleton locks from previous unclean shutdowns
        for (const lockName of ['SingletonLock', 'SingletonSocket', 'SingletonCookie']) {
            try { fs.unlinkSync(path.join(this.profileDir, lockName)); } catch {}
        }

        const port = pickPort();
        const args = [
            `--user-data-dir=${this.profileDir}`,
            '--profile-directory=Default',
            `--remote-debugging-port=${port}`,
            '--no-first-run',
            '--no-default-browser-check',
            '--disable-features=DestroyProfileOnBrowserClose,NotificationTriggers,PushMessaging',
            '--disable-session-crashed-bubble',
            '--disable-infobars',
            '--disable-notifications',
            '--deny-permission-prompts',
            // Land directly on Google login page with YouTube as the destination service
            'https://accounts.google.com/ServiceLogin?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F'
        ];

        onLog('launching Chrome with dedicated YouTube profile...');
        const proc = spawn(chromePath, args, {
            detached: false, stdio: 'ignore', windowsHide: false
        });
        this._activeProc = proc;
        proc.on('exit', () => {
            if (this._activeProc === proc) this._activeProc = null;
        });

        let wsUrl;
        try {
            wsUrl = await waitForDebugPort(port);
        } catch (e) {
            try { proc.kill(); } catch {}
            this._activeProc = null;
            throw new Error('Chrome debug port unreachable: ' + e.message);
        }

        const browser = await puppeteer.connect({
            browserWSEndpoint: wsUrl, defaultViewport: null
        });
        this._activeBrowser = browser;

        try {
            return await this._waitForLoginAndCapture(browser, { timeoutMs, onLog });
        } finally {
            // Close puppeteer connection but leave the Chrome process alone
            // (it'll be killed when we explicitly call closeWindow).
            try { browser.disconnect(); } catch {}
            this._activeBrowser = null;
        }
    }

    async _waitForLoginAndCapture(browser, { timeoutMs, onLog }) {
        const start = Date.now();
        let bestSnapshot = null;      // latest cookies that at least have Google auth
        let goodCheckCount = 0;       // consecutive checks where BOTH Google + YouTube present
        let navigatedToYt = false;    // only force-navigate once

        while (Date.now() - start < timeoutMs) {
            // User manually closed the Chrome window — use the best snapshot we
            // saw so far. This handles the "let me verify I'm on YouTube and
            // close it myself" flow that users want.
            const procDead = !this._activeProc;
            const browserDead = !browser.connected;
            if (procDead || browserDead) {
                if (bestSnapshot) {
                    onLog(`window closed — saving best snapshot (${bestSnapshot.length} cookies)`);
                    return this._saveCookies(bestSnapshot);
                }
                throw new Error('User closed the window before any login cookies were captured');
            }

            let cookies = [];
            try { cookies = await browser.cookies(); }
            catch (e) { onLog(`browser.cookies() failed: ${e.message}`); }

            const hasGoogleAuth = cookies.some(c =>
                GOOGLE_AUTH_COOKIES.includes(c.name) && (c.domain || '').includes('google'));
            const hasYouTubeSession = cookies.some(c =>
                c.name === YOUTUBE_SESSION_COOKIE && (c.domain || '').includes('youtube'));

            // Remember the latest snapshot that has at least Google auth — falls
            // back to this if user closes early or times out.
            if (hasGoogleAuth) bestSnapshot = cookies;

            if (hasGoogleAuth && hasYouTubeSession) {
                goodCheckCount++;
                onLog(`✓ Google + YouTube cookies both present (check ${goodCheckCount}/3)`);
                // Wait for 3 consecutive successful polls (~6s) so any trailing
                // redirect/cookie sets land before we capture and close.
                if (goodCheckCount >= 3) {
                    onLog(`finalizing — saving ${cookies.length} cookies and closing Chrome`);
                    this.closeWindow();
                    await sleep(500);
                    return this._saveCookies(cookies);
                }
            } else {
                goodCheckCount = 0;
                // User logged into Google but hasn't reached youtube.com → kick
                // the first page over to www.youtube.com so YouTube can set
                // LOGIN_INFO. Only attempt once to avoid disrupting the user.
                if (hasGoogleAuth && !navigatedToYt) {
                    navigatedToYt = true;
                    await this._nudgeToYouTube(browser, onLog);
                }
            }
            await sleep(2000);
        }

        // Hard timeout
        if (bestSnapshot) {
            onLog(`timeout — falling back to best snapshot (${bestSnapshot.length} cookies)`);
            this.closeWindow();
            return this._saveCookies(bestSnapshot);
        }
        this.closeWindow();
        throw new Error(`login timed out after ${Math.round(timeoutMs / 1000)}s — user never completed login`);
    }

    // After Google login redirects somewhere other than youtube.com (often
    // a Google account picker / continue page) the YouTube session cookie is
    // never set. Force navigation so LOGIN_INFO gets populated.
    async _nudgeToYouTube(browser, onLog) {
        try {
            const pages = await browser.pages();
            const page = pages[0];
            if (!page) return;
            const url = page.url();
            if (!/(^|\.)youtube\.com/.test(new URL(url).hostname || '')) {
                onLog(`Google authenticated — nudging to youtube.com (was ${url})`);
                await page.goto('https://www.youtube.com/', { waitUntil: 'domcontentloaded', timeout: 20000 })
                    .catch(e => onLog(`nudge nav failed: ${e.message}`));
            }
        } catch (e) {
            onLog(`nudge skipped: ${e.message}`);
        }
    }

    _saveCookies(cookies) {
        const text = cookiesToNetscape(cookies);
        fs.writeFileSync(this.cookiesPath, text, 'utf8');
        if (this.db) {
            this.db.prepare(
                `INSERT INTO settings (key, value) VALUES ('youtube_cookies_path', ?)
                 ON CONFLICT(key) DO UPDATE SET value = excluded.value`
            ).run(this.cookiesPath);
        }
        return { ok: true, cookies_count: cookies.length, path: this.cookiesPath };
    }

    // Kill the Chrome window (used by both timeout and explicit cancel)
    closeWindow() {
        if (this._activeProc) {
            try { this._activeProc.kill(); } catch {}
            this._activeProc = null;
        }
    }

    // Wipe cookies.txt + profile dir so next login starts fresh
    async logout() {
        this.closeWindow();
        try { if (fs.existsSync(this.cookiesPath)) fs.unlinkSync(this.cookiesPath); } catch {}
        try {
            if (fs.existsSync(this.profileDir)) {
                fs.rmSync(this.profileDir, { recursive: true, force: true });
                fs.mkdirSync(this.profileDir, { recursive: true });
            }
        } catch (e) {
            console.warn('[youtubeLogin] failed to wipe profile dir:', e.message);
        }
        if (this.db) {
            this.db.prepare(`DELETE FROM settings WHERE key = 'youtube_cookies_path'`).run();
        }
        return { ok: true };
    }
}

module.exports = { YouTubeLoginService };
